prose:
  metadata:
    wiki:
      - name: "layout"
        field:
          element: "hidden"
          value: "default"
#  siteurl: "http://collaborativeinter.net/"
#  rooturl: "wiki"
  media: "media"
